name: Our first python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  my-first-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: python -m pip install --upgrade pip uv

      - name: Install the project dependencies using uv
        run: uv sync --locked --all-extras --dev

      - name: Lint with Ruff
        run: uv run ruff check .

      - name: Test with pytest
        run: uv run pytest tests

